## week 2-3 preprocessing homework draft
#### customer transactions dataset preprocessing notebook

digma, ronachel marie of h3101

### import libraries and dataset

In [2]:
import pandas as pd
import numpy as np

# load dataset

transactions = pd.read_csv('../../data/raw/customer_transactions_contaminated.csv')

### inspect

In [3]:
# inspect dataset
print("First 20 rows: ")
display(transactions.head(20))

print("\nDataset Information: ")
display(transactions.info())

print("\nDataset Dimensions: ")
display(transactions.shape)

print("\nDataset Columns: ")
display(transactions.columns)

print("\nDataset Numerical Statistics: ")
display(transactions.describe())

First 20 rows:

,CustomerID,TransactionID,TransactionDate,Amount,ProductCategory,PaymentMethod
0,60567026-f719-4cd6-849e-137e86d8938f,5ff75116-0a50-4d04-80fb-31e5ccbb0769,2024-05-15,117.64,Clothing,PayPal
1,4090ba85-b111-4f75-a792-c777965f5255,2c39b9fe-ff57-4d39-9321-9f5cdf187aa1,2023-04-26,466.14,Health & Beauty,Bank Transfer
2,9223891b-73ff-4d5c-b8ae-13ece82ee28b,f79588dd-3db9-4ffa-97f8-7de0e64259f1,2022-09-23,563.99,Clothing,Debit Card
3,9243eebc-938f-480c-8564-16d503d250de,401c0fc9-60df-4455-ad78-67c132f9897d,2024-04-15,254.44,Automotive,PayPal
4,6e3e8eb8-bc0f-4ffe-9f74-5d5efec9502f,2034aebc-8280-4254-a667-92bcd1c2be4f,2024-06-03,590.52,Home & Garden,Bank Transfer
5,3eccdcf9-e8ce-4e44-9f62-8bef88e70672,78dfb45e-16e0-4ecc-8f67-f2e210c31c3e,2024-04-07,Free,NaN,Credit Card
6,7fbc5847-a652-4fc8-a7d8-5e85d846e91b,591f1ea2-c97d-44dd-9539-71ac89b94ff3,2024-01-12,NaN,Automotive,PayPal
7,958e5c8d-48ca-42dd-bb71-a766a374233a,fb24e098-3ab9-40a2-bcc3-b8ebb23f549a,2023-03-10,399.7,Home & Garden,PayPal
8,39c6e7d2-6c4b-44c0-8961-ddc1ecbdb0c6,833b026a-7c02-4101-832d-62c07569b0f6,2024-01-26,296.99,Clothing,PayPal
9,474f9233-0616-431b-b3e9-a6feabe68abb,f8bde21a-7a6b-41f6-ac39-eeb77640fa9b,2023-06-15,149.39,Clothing,Debit Card
10,187ec535-ad79-418a-aa08-86fd8a2becbb,85dc5e9e-1bd7-44e3-9a13-980736fedd3c,2023-06-01,255.41,Health & Beauty,Bank Transfer
11,848f7178-b94b-4d8e-8baa-6a3886828887,80cd99c4-01c7-47ec-8272-79250c1c4725,2024-03-09,813.81,Electronics,Credit Card
12,c3a5e86e-a74b-420e-b1e7-13bcbe6b71ac,e101f309-f9f8-4856-aa30-0153aa5f368c,2022-11-06,989.99,Electronics,Debit Card
13,0e09f085-80ce-47c9-9fb2-e936ef0e9065,65267198-f460-4051-95dc-a491fa1cab66,2024-01-28,158.35,Electronics,Bank Transfer
14,28c29c18-0cbe-40ea-b218-a96430cc4409,deaec587-bd63-4556-8cea-e9d297f6651e,2023-11-08,140.88,Automotive,Credit Card
15,68b5a27d-980f-409d-9b64-acc242c86f8e,3d5a459b-4b31-4fab-ab67-8d846e07471f,2022-07-24,775.43,Electronics,Credit Card
16,54b3556e-e480-41a2-9dcd-7da1d91655aa,c181a599-fcc7-4f9b-b618-783684e0fd24,2023-03-06,861.39,Clothing,Bank Transfer
17,decfbb11-2324-4a91-b4a4-da3011046f88,3dd5070c-5644-408f-bc17-15bf71f345a5,2024-04-17,130.53,Electronics,PayPal
18,5dfe3352-ee78-4510-a968-9aba1dd940a2,f68315c9-1273-4ae3-8f0b-0479bc90cb5b,2023-05-02,140.01,Health & Beauty,Bank Transfer
19,be854a65-4191-467a-9237-60b4e088df5b,b5d01bad-fb0a-4d50-8aa5-8f84c554096b,2023-12-27,478.53,Clothing,Bank Transfer

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3200 entries, 0 to 3199
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerID       3200 non-null   object
 1   TransactionID    3200 non-null   object
 2   TransactionDate  3200 non-null   object
 3   Amount           2896 non-null   object
 4   ProductCategory  2901 non-null   object
 5   PaymentMethod    3200 non-null   object
dtypes: object(6)
memory usage: 150.1+ KB

None

Dataset Dimensions:

(3200, 6)

Dataset Columns:

Index(['CustomerID', 'TransactionID', 'TransactionDate', 'Amount',
       'ProductCategory', 'PaymentMethod'],
      dtype='object')

Dataset Numerical Statistics:

,CustomerID,TransactionID,TransactionDate,Amount,ProductCategory,PaymentMethod
count,3200,3200,3200,2896,2901,3200
unique,1871,3000,808,2603,5,4
top,49f06ea9-4ae5-4ce5-98ce-d2c2f6f15cbd,5ff75116-0a50-4d04-80fb-31e5ccbb0769,2024-01-06,-100,Clothing,Debit Card
freq,7,2,13,39,598,809

### exact duplicate records

In [4]:
# inspect duplicates
duplicate_transactions = transactions.duplicated().sum()

print("Exact duplicate rows:", duplicate_transactions)

display(transactions[transactions.duplicated(keep=False)])

Exact duplicate rows: 185

,CustomerID,TransactionID,TransactionDate,Amount,ProductCategory,PaymentMethod
0,60567026-f719-4cd6-849e-137e86d8938f,5ff75116-0a50-4d04-80fb-31e5ccbb0769,2024-05-15,117.64,Clothing,PayPal
9,474f9233-0616-431b-b3e9-a6feabe68abb,f8bde21a-7a6b-41f6-ac39-eeb77640fa9b,2023-06-15,149.39,Clothing,Debit Card
16,54b3556e-e480-41a2-9dcd-7da1d91655aa,c181a599-fcc7-4f9b-b618-783684e0fd24,2023-03-06,861.39,Clothing,Bank Transfer
36,9560ed71-7a04-4cd9-a576-b622c5690487,ad529898-c1b5-4fe7-b30b-a9f19c666386,2024-05-31,833.48,Automotive,Bank Transfer
45,d3493edf-9847-46ef-b400-7063b54bcf63,6fa36483-8ac7-4af8-9cc7-e0607673f331,2022-07-15,119.65,Clothing,PayPal
...,...,...,...,...,...,...
3195,59f8afe5-173b-4e52-b641-f98183f1a891,3121df10-58e5-4ed4-a05c-b1f12df6bcc7,2023-01-18,892.44,Home & Garden,Bank Transfer
3196,16d0b561-279d-4da9-9aa8-8c5906dff79a,dff4f636-2c55-4237-8c55-efb15b05949b,2024-02-13,431.64,Health & Beauty,Credit Card
3197,34e3f558-622e-4d6b-8d5d-07ab632e1b95,db0a4640-ea96-4fcd-989b-b71ba767529c,2022-12-26,NaN,Home & Garden,PayPal
3198,d83178cf-653d-435c-a7e8-880361dec6e7,89a1c0bc-4d49-4913-bb0f-26bd56b46a34,2022-09-26,343.46,Health & Beauty,Debit Card
3199,d64b0c8d-1831-4b29-baa2-08c4d5c3a0f9,6c47f481-3a5c-49bc-ab1d-2b198394b2e8,2023-06-20,NaN,Electronics,Debit Card

In [5]:
# drop exact duplicate records
transactions_cleaned = transactions.drop_duplicates().copy()

# verify and check shape 
print("Duplicates remaining:", transactions_cleaned.duplicated().sum())
print("Dataset shape after removal of duplicates:", transactions_cleaned.shape)

Duplicates remaining: 0
Dataset shape after removal of duplicates: (3015, 6)

In [6]:
# inspect whether any non-identical records still share a transaction id
print("Unique TransactionIDs:", transactions_cleaned["TransactionID"].nunique())
print("Duplicate TransactionIDs:", transactions_cleaned["TransactionID"].duplicated().sum())

Unique TransactionIDs: 3000
Duplicate TransactionIDs: 15

In [7]:
# inspect whether those 15 id's are duplicate copies of the same transaction with some corrupted/different field, or genuinely different transactions that were accidentally given the same id
duplicate_transaction_ids = transactions_cleaned[transactions_cleaned["TransactionID"].duplicated(keep=False)].sort_values("TransactionID")
display(duplicate_transaction_ids)

,CustomerID,TransactionID,TransactionDate,Amount,ProductCategory,PaymentMethod
2118,778da54b-8f96-4609-a21b-bba3d7f071ea,022cfd97-a8e8-4e50-8700-2720d52bfd75,2022-08-23,586.87,Health & Beauty,PayPal
3005,778da54b-8f96-4609-a21b-bba3d7f071ea,022cfd97-a8e8-4e50-8700-2720d52bfd75,2022-08-23,Free,Health & Beauty,PayPal
3174,6a84f1a7-f636-4300-bd8d-c7f888460829,185ee140-348a-4461-bd40-07a7e8535815,2023-10-09,0,Health & Beauty,PayPal
413,6a84f1a7-f636-4300-bd8d-c7f888460829,185ee140-348a-4461-bd40-07a7e8535815,2023-10-09,953.86,Health & Beauty,PayPal
3038,b94b3531-591d-445c-b282-dcacb0baca5b,27fb25aa-f148-423f-967c-4d1764e26b29,2024-04-18,-100,Automotive,Credit Card
431,b94b3531-591d-445c-b282-dcacb0baca5b,27fb25aa-f148-423f-967c-4d1764e26b29,30/07/2022,506.96,Automotive,Credit Card
2081,e7cf6999-b4ec-4ce4-bb09-bfd18d61d933,2e0b66a9-af5d-4cf9-bb60-55ab2932edee,2023-05-10,504.42,Electronics,Bank Transfer
3073,e7cf6999-b4ec-4ce4-bb09-bfd18d61d933,2e0b66a9-af5d-4cf9-bb60-55ab2932edee,2023-05-10,-100,Electronics,Bank Transfer
3050,a9af986b-d677-421a-81df-3d289ce9e38f,5f93f1dc-0363-4e69-979b-f5d58fd42658,2023-09-30,-100,NaN,Bank Transfer
220,a9af986b-d677-421a-81df-3d289ce9e38f,5f93f1dc-0363-4e69-979b-f5d58fd42658,2023-09-30,125.77,NaN,Bank Transfer
3123,8de3d5b9-1f1a-4bd7-b242-6cb09d7f3609,5fca256b-cd5a-48fa-8b07-37f39adde8c9,2023-05-17,-100,Clothing,Bank Transfer
1093,8de3d5b9-1f1a-4bd7-b242-6cb09d7f3609,5fca256b-cd5a-48fa-8b07-37f39adde8c9,2023-05-17,764.92,Clothing,Bank Transfer
2371,321acf6c-c401-4f7b-9835-bfb7cd5e48ff,62186b07-9cda-44c5-bf76-bdb0f97aaf39,05/04/2023,NaN,Home & Garden,Bank Transfer
3094,321acf6c-c401-4f7b-9835-bfb7cd5e48ff,62186b07-9cda-44c5-bf76-bdb0f97aaf39,2023-02-04,NaN,Home & Garden,Bank Transfer
629,086370e7-8884-47d7-89b0-776401a43e1c,652636b6-5c72-44e1-aefb-6adce412ee75,2023-12-05,0,Electronics,Debit Card
3153,086370e7-8884-47d7-89b0-776401a43e1c,652636b6-5c72-44e1-aefb-6adce412ee75,2023-12-05,974.25,Electronics,Debit Card
3048,1ffded5f-b38d-45b7-943d-4100779c3599,6c2c5c2b-7601-41dc-9f56-4009de6f3cea,2023-05-10,591.61,Clothing,Debit Card
2690,1ffded5f-b38d-45b7-943d-4100779c3599,6c2c5c2b-7601-41dc-9f56-4009de6f3cea,10/06/2024,591.61,Clothing,Debit Card
3105,4aab54a1-b555-48ec-9b0f-0e87abdcc45b,7202af3a-448f-4970-9674-40f736cfdfde,27/03/2024,634.41,NaN,PayPal
283,4aab54a1-b555-48ec-9b0f-0e87abdcc45b,7202af3a-448f-4970-9674-40f736cfdfde,2023-02-26,634.41,NaN,PayPal
940,79fc606a-c02c-4c39-b065-3e88a59b366c,7fbe5cc4-a35e-4e8e-89d7-7b439659b9f6,2022-07-14,272.68,Clothing,Debit Card
3164,79fc606a-c02c-4c39-b065-3e88a59b366c,7fbe5cc4-a35e-4e8e-89d7-7b439659b9f6,20/07/2022,272.68,Clothing,Debit Card
2610,3ea377e6-1156-457e-8b4e-71fa6663e6bf,c751a808-ed8d-44d0-8c52-8253ad564c9a,2023-09-22,766.97,Health & Beauty,Credit Card
3177,3ea377e6-1156-457e-8b4e-71fa6663e6bf,c751a808-ed8d-44d0-8c52-8253ad564c9a,2023-09-22,-100,Health & Beauty,Credit Card
1639,24b043e8-6fca-4d86-95a8-837e0ca09072,dc9453eb-3922-4a5f-91c0-ccb226ca91f7,2023-06-01,446.84,Health & Beauty,Debit Card
3012,24b043e8-6fca-4d86-95a8-837e0ca09072,dc9453eb-3922-4a5f-91c0-ccb226ca91f7,2023-06-01,-100,Health & Beauty,Debit Card
807,7c7df909-aa25-48c7-af9d-6ebe714b28b6,eb26a4f4-5af2-4e25-b1f2-fd0de5583f7b,2023-03-23,50.07,Automotive,Bank Transfer
3157,7c7df909-aa25-48c7-af9d-6ebe714b28b6,eb26a4f4-5af2-4e25-b1f2-fd0de5583f7b,10/08/2022,50.07,Automotive,Bank Transfer
3113,f05ec030-ac96-417d-a73c-e3ca3adc1a30,f39c8b1d-595a-4656-8108-25981bf3fa14,2024-03-05,252.7,Electronics,Debit Card
563,f05ec030-ac96-417d-a73c-e3ca3adc1a30,f39c8b1d-595a-4656-8108-25981bf3fa14,03/04/2023,-100,Electronics,Debit Card

In [11]:
# check how many rows each duplicated id has
duplicate_transaction_ids["TransactionID"].value_counts()

TransactionID
022cfd97-a8e8-4e50-8700-2720d52bfd75    2
185ee140-348a-4461-bd40-07a7e8535815    2
27fb25aa-f148-423f-967c-4d1764e26b29    2
2e0b66a9-af5d-4cf9-bb60-55ab2932edee    2
5f93f1dc-0363-4e69-979b-f5d58fd42658    2
5fca256b-cd5a-48fa-8b07-37f39adde8c9    2
62186b07-9cda-44c5-bf76-bdb0f97aaf39    2
652636b6-5c72-44e1-aefb-6adce412ee75    2
6c2c5c2b-7601-41dc-9f56-4009de6f3cea    2
7202af3a-448f-4970-9674-40f736cfdfde    2
7fbe5cc4-a35e-4e8e-89d7-7b439659b9f6    2
c751a808-ed8d-44d0-8c52-8253ad564c9a    2
dc9453eb-3922-4a5f-91c0-ccb226ca91f7    2
eb26a4f4-5af2-4e25-b1f2-fd0de5583f7b    2
f39c8b1d-595a-4656-8108-25981bf3fa14    2
Name: count, dtype: int64

after removing exact duplicate rows, 15 transaction ids were still associated with two different records. these records were inspected and found to contain differences in fields such as transaction date and amount. since the records are not exact duplicates, they were retained rather than arbitrarily deleting one record from each pair. the inconsistent transaction id values will be documented as data-quality issues.

### missing, invalid, and inconsistent values

#### amount

In [12]:
# inspect amount column distribution
print("Amount Values:")
display(transactions_cleaned["Amount"].value_counts(dropna=False).sort_index())
print("\nAmount Data Type:", transactions_cleaned["Amount"].dtype)

Amount Values:

Amount
-100       39
-100.0      1
0          29
0.0         1
10.03       1
         ...
999.55      1
999.56      1
999.86      2
Free       30
NaN       283
Name: count, Length: 2604, dtype: int64

Amount Data Type: object

In [13]:
# convert amount values to numeric to properly analyze
transactions_cleaned["Amount"] = pd.to_numeric(transactions_cleaned["Amount"], errors="coerce")

# verify
print("Amount Column Data Type:", transactions_cleaned["Amount"].dtype)
print("\nMissing Amount Values:", transactions_cleaned["Amount"].isna().sum())

Amount Column Data Type: float64

Missing Amount Values: 313